apiVersion: v1
kind: Service
metadata:
  name: {{ include "baby-counter.fullname" . }}
  labels:
    {{- include "baby-counter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "baby-counter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
